[[trains]]
id = "P1"
path = [ [0, 1,], [0, 2,], [0, 3,], [ 0, 4,], [ 0, 5,], [ 1, 5,], [ 2, 5,], [ 3, 5,], [ 4, 5,], [ 5, 5,], [ 6, 5,], [ 7, 5,], [ 8, 5,], [ 9, 5,], [ 10, 5,], [ 11, 5,], [ 12, 5,], [ 13, 5,], [ 14, 5,], [ 15, 5,], [ 16, 5,], [ 16, 6,], [ 16, 7,], [ 16, 8,], [ 16, 9,],]
[[trains.cars]]
bg_color = "blue"

[[trains.cars]]
bg_color = "lightblue"

[[trains.cars]]
bg_color = "lightblue"


[[trains]]
id = "P2"
path = [ [ 16, 0,], [ 16, 1,], [ 16, 2,], [ 16, 3,], [ 16, 4,], [ 16, 5,], [ 15, 5,], [ 14, 5,], [ 13, 5,], [ 12, 5,], [ 11, 5,], [ 10, 5,], [ 9, 5,], [ 8, 5,], [ 8, 4,], [ 8, 3,], [ 8, 2,], [ 8, 1,], [ 8, 0,], [ 7, 0,], [ 6, 0,], [ 5, 0,], [ 4, 0,], [ 3, 0,], [ 2, 0,], [ 1, 0,],]
[[trains.cars]]
bg_color = "red"

[[trains.cars]]
bg_color = "lightred"

[[trains.cars]]
bg_color = "lightred"


[[trains]]
id = "P3"
path = [ [ 16, 10,], [ 15, 10,], [ 14, 10,], [ 13, 10,], [ 12, 10,], [ 11, 10,], [ 10, 10,], [ 9, 10,], [ 8, 10,], [ 8, 9,], [ 8, 8,], [ 8, 7,], [ 8, 6,], [ 8, 5,], [ 7, 5,], [ 6, 5,], [ 5, 5,], [ 4, 5,], [ 3, 5,], [ 2, 5,], [ 1, 5,], [ 0, 5,], [ 0, 4,], [ 0, 3,], [ 0, 2,], [ 0, 1,], [ 0, 0,],]
[[trains.cars]]
bg_color = "yellow"

[[trains.cars]]
bg_color = "yellow"

[[trains.cars]]
bg_color = "yellow"
