/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.openjfx.javafxplugin") version "0.0.13"
    id("com.diffplug.spotless") version "6.5.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.1")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.0.1-jre")
    implementation("org.yaml:snakeyaml:2.0")
    implementation("org.openjfx:javafx-controls:19")
    implementation("org.openjfx:javafx-swing:19")
    implementation("org.openjfx:javafx-web:19")
    implementation("org.openjfx:javafx-fxml:19")
    implementation("org.apache.xmlgraphics:batik-all:1.14")
    implementation("org.apache.xmlgraphics:batik-svggen:1.14")
    implementation("org.apache.xmlgraphics:batik-transcoder:1.14")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

javafx {
    version = "19"
    modules = listOf("javafx.controls", "javafx.swing", "javafx.web", "javafx.fxml")
}

spotless {
    java {
        googleJavaFormat("1.10.0")
        target("app/**/*.java")
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}
